services:
  - type: web
    name: relatorios-backend
    plan: free
    runtime: python
    pythonVersion: "3.9.13"  # ⚠️ Versão compatível
    
    buildCommand: |
      cd backend && \
      poetry config virtualenvs.create false && \
      poetry install --no-interaction --no-root --only main
      
    startCommand: |
      cd backend && \
      poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
