services:
  - type: web
    name: relatorios-backend
    plan: free
    runtime: python
    pythonVersion: "3.9.13"
    
    buildCommand: |
      cd Backend && \
      poetry install --no-root --only main
      
    startCommand: |
      cd Backend && \
      poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
